apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: vitaliy1yeremenko/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: vitaliy1yeremenko/ticketing-client
      context: client
      sync:
        manual:
          - src: '**/*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: vitaliy1yeremenko/tickets
      context: tickets
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: vitaliy1yeremenko/orders
      context: orders
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: vitaliy1yeremenko/expiration
      context: expiration
      sync:
        manual:
          - src: src/***/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: vitaliy1yeremenko/payments
      context: payments
      sync:
        manual:
          - src: src/***/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
